/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.EditoraBEAN;
import static view.Biblioteca_V10.controle;

/**
 *
 * @author - Felipe Peretti -
 */
public class Editora extends javax.swing.JFrame {
    
    DefaultTableModel modelo;
    List<EditoraBEAN> lista_editoras;
    
    
    public Editora() {
        initComponents();
        
        this.setButton(false, false, false);
        
        modelo = (DefaultTableModel) tabela_editoras.getModel();
        lista_editoras = controle.listaEditoras();
        preencher_tabela(lista_editoras);
    }
    
    private String toStatus(boolean status){
        if (status) {
            return "ATIVO";
        }
        return "INATIVO";
    }
    
    
    public void preencher_tabela(List<EditoraBEAN> listEditoras){

        tabela_editoras.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabela_editoras.getColumnModel().getColumn(1).setPreferredWidth(700);
        tabela_editoras.getColumnModel().getColumn(2).setPreferredWidth(600);
        tabela_editoras.getColumnModel().getColumn(3).setPreferredWidth(500);
        tabela_editoras.getColumnModel().getColumn(4).setPreferredWidth(400);
        
        modelo.setNumRows(0);

        try{
            for(EditoraBEAN editora : listEditoras){
                modelo.addRow(new Object[]{editora.getid_editora(),editora.getRazao_social(),editora.getEndereco()
                ,editora.getTelefone(),toStatus(editora.getStatus())});
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null,"Erro ao listar dados - "+erro);
        }
    }
    
    public void preencher_tabela(EditoraBEAN editora){
        tabela_editoras.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabela_editoras.getColumnModel().getColumn(1).setPreferredWidth(700);
        tabela_editoras.getColumnModel().getColumn(2).setPreferredWidth(600);
        tabela_editoras.getColumnModel().getColumn(3).setPreferredWidth(500);
        tabela_editoras.getColumnModel().getColumn(4).setPreferredWidth(400);
        
        modelo.setNumRows(0);
        
        try{
            modelo.addRow(new Object[]{editora.getid_editora(),editora.getRazao_social(),editora.getEndereco()
            ,editora.getTelefone(),toStatus(editora.getStatus())});    
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null,"Erro ao listar dados - "+erro);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_editoras = new javax.swing.JTable();
        _nome = new javax.swing.JLabel();
        t_nome = new javax.swing.JTextField();
        _nome1 = new javax.swing.JLabel();
        t_codigo = new javax.swing.JTextField();
        bt_inserir = new javax.swing.JButton();
        bt_alterar = new javax.swing.JButton();
        bt_ativar = new javax.swing.JButton();
        bt_desativar = new javax.swing.JButton();
        bt_buscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editora");

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        tabela_editoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Razão Social", "Endereço", "Telefone", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_editoras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tabela_editorasFocusLost(evt);
            }
        });
        tabela_editoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_editorasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_editoras);
        if (tabela_editoras.getColumnModel().getColumnCount() > 0) {
            tabela_editoras.getColumnModel().getColumn(0).setResizable(false);
            tabela_editoras.getColumnModel().getColumn(1).setResizable(false);
            tabela_editoras.getColumnModel().getColumn(2).setResizable(false);
            tabela_editoras.getColumnModel().getColumn(3).setResizable(false);
            tabela_editoras.getColumnModel().getColumn(4).setResizable(false);
        }

        _nome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        _nome.setText("Razão Social: ");

        _nome1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        _nome1.setText("Código:");

        t_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_codigoActionPerformed(evt);
            }
        });

        bt_inserir.setText("Inserir");
        bt_inserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_inserirMouseClicked(evt);
            }
        });

        bt_alterar.setText("Alterar");
        bt_alterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_alterarMouseClicked(evt);
            }
        });

        bt_ativar.setText("Ativar");
        bt_ativar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ativarMouseClicked(evt);
            }
        });

        bt_desativar.setText("Desativar");
        bt_desativar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_desativarMouseClicked(evt);
            }
        });

        bt_buscar.setText("Buscar");
        bt_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_buscarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Editora");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(bt_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(98, 98, 98)
                            .addComponent(bt_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_ativar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(85, 85, 85)
                            .addComponent(bt_desativar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(_nome)
                                .addComponent(_nome1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(t_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_buscar))))
                        .addComponent(jSeparator1)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_buscar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_desativar)
                    .addComponent(bt_ativar)
                    .addComponent(bt_alterar)
                    .addComponent(bt_inserir))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_codigoActionPerformed
    
    private void setButton(boolean b1, boolean b2, boolean b3){
        this.bt_alterar.setEnabled(b1);
        this.bt_ativar.setEnabled(b2);
        this.bt_desativar.setEnabled(b3);
    }
    
    
    private void bt_inserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_inserirMouseClicked

       CadastraAlteraEditora cadastro = new CadastraAlteraEditora(this);       
       cadastro.show();
   
    }//GEN-LAST:event_bt_inserirMouseClicked

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown

    }//GEN-LAST:event_jPanel1ComponentShown

    private void bt_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_buscarMouseClicked
        if (!t_nome.getText().equals("")) {
            preencher_tabela(controle.listaLikeNameEditora(t_nome.getText()));
        }else if (!t_codigo.getText().equals("")) {
            preencher_tabela(controle.findEditora(Integer.parseInt(t_codigo.getText())));
        }else{
            preencher_tabela(lista_editoras);
        }
    }//GEN-LAST:event_bt_buscarMouseClicked

    private void tabela_editorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_editorasMouseClicked
        int linha = tabela_editoras.getSelectedRow();
        String status = (String) tabela_editoras.getValueAt(linha, 4);
        if (status.equals("ATIVO")) {
            this.setButton(true, false, true);
        }else{
            this.setButton(true, true, false);
        }
    }//GEN-LAST:event_tabela_editorasMouseClicked

    private void tabela_editorasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabela_editorasFocusLost
        this.setButton(false, false, false);
    }//GEN-LAST:event_tabela_editorasFocusLost

    private void bt_ativarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ativarMouseClicked
        int linha = tabela_editoras.getSelectedRow();
        int id = (int) tabela_editoras.getValueAt(linha, 0);
        EditoraBEAN aux = controle.findEditora(id);
        aux.setStatus(true);
        controle.updateEditora(aux);
        preencher_tabela(controle.listaEditoras());
    }//GEN-LAST:event_bt_ativarMouseClicked

    private void bt_desativarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_desativarMouseClicked
        int linha = tabela_editoras.getSelectedRow();
        int id = (int) tabela_editoras.getValueAt(linha, 0);
        EditoraBEAN aux = controle.findEditora(id);
        aux.setStatus(false);
        controle.updateEditora(aux);
        preencher_tabela(controle.listaEditoras());
    }//GEN-LAST:event_bt_desativarMouseClicked

    private void bt_alterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_alterarMouseClicked
        int linha = tabela_editoras.getSelectedRow();
        int id = (int) tabela_editoras.getValueAt(linha, 0);
        CadastraAlteraEditora cadastro = new CadastraAlteraEditora(this, id);       
        cadastro.show();
    }//GEN-LAST:event_bt_alterarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _nome;
    private javax.swing.JLabel _nome1;
    private javax.swing.JButton bt_alterar;
    private javax.swing.JButton bt_ativar;
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_desativar;
    private javax.swing.JButton bt_inserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField t_codigo;
    private javax.swing.JTextField t_nome;
    private javax.swing.JTable tabela_editoras;
    // End of variables declaration//GEN-END:variables
}
